apiVersion: v1
kind: ConfigMap
metadata:
  name: marginalia-backend-config
  namespace: marginalia
data:
  PORT: "5000"
  JWT_EXPIRES_IN: "7d"
  CLIENT_URL: "http://k8s-marginal-marginal-a7ef95e2a5-1295257203.us-east-1.elb.amazonaws.com"   # update once you have a real domain/ALB DNS
