apiVersion: v1
kind: Secret
metadata:
  name: marginalia-backend-secrets
  namespace: marginalia
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://timothyolasunkanmi:holasunkanmi@mern-blog-app.xr34cfl.mongodb.net/mernblog?retryWrites=true&w=majority&appName=mern-blog-app
  JWT_SECRET: cad94e53e98d169e31a8fbc1b570e905b3c3cd9933f52b153a0ce9d4fb52d464